[tool.poetry]
name = "yalyceum"
version = "0.1.0"
description = ""
authors = ["gleb <zzu1u@list.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
